services:
  jupyter:
    image: jupyter/base-notebook:latest
    ports:
      - '8888:8888'
    env_file:
      - .env
    volumes:
      - .:/home/jovyan/work
    command:
      [
        'jupyter',
        'lab',
        '--ip=0.0.0.0',
        '--port=8888',
        '--no-browser',
        '--allow-root',
        "--ServerApp.token=''",
      ]
